spring.application.name=ruleEngine

#Do not change
spring.datasource.url=jdbc:mysql://mysqldb:3306/rule_engine

#Recommed to use root
spring.datasource.username=root

#Change password with root password
#Similar password to add in docker-compose
spring.datasource.password=9423635767

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true